# Generated by Django 4.1.13 on 2024-05-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
